### ISSUE TITLE
subiquity/Proxy/load_autoinstall_data http_proxy is not of type 'string', 'null'

### ISSUE THREAD

**Issue by Comnenus** [canonical/autoinstall-desktop#14]
Following the proxy section in the curtin doc: https://curtin.readthedocs.io/en/latest/topics/config.html and using Ubuntu 22.04.4, I have added the following section underneath the # proxy: comment in autoinstall.yaml:

```
proxy:
  http_proxy: 'http://myproxy.mydomain.com:8080/'
  https_proxy: 'http://myproxy.mydomain.com:8080/'
  no_proxy: 'some_exception,.mydomain.com'
```

But this is not parsing correctly.  I am receiving the following errors:

```
connecting...
waiting for cloud-init...
running early commands
  running echo 'linux-generic-hwe-22.94' > /run/kernel-meta-package
finish: subiquity/Proxy/load_autoinstall_data: {'http_proxy': 'http://myproxy.mydomain.com:8080/', 'https_proxy': 'http://myproxy.mydomain.com:8080/', 'no_proxy': 'some_exception,.mydomain.com'} is not of type 'string', 'null'

Failed validating 'type' in schema:
    {'format': 'uri', 'type': ['string', 'null']}
```

Am I forming this correctly?  I have gone over the curtin doc several times and am not seeing the problem.
