### ISSUE TITLE
languages

### ISSUE THREAD

**Issue by ubuntushopdoteu** [canonical/autoinstall-desktop#15]
I am now testing the new installer for autoinstall, but on gnome user setup (because no user exists), end user cannot choose language and there is only a few keyboard layouts to choose from.
Is there a way to autointall all keyboard layouts and languages via the autoinstall.yaml file?

**Comment by maksimsamt** [comment]
Try this autoinstall section:
https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html#keyboard

For instance:

```yaml
...
  keyboard:
    layout: "fr,us"
    toggle: "alt_shift_toggle"
    # or this if previous doesn't work
    # toggle: "grp:alt_shift_toggle"
    variant: ","
...
```
